name: "Setup GCC"
description: "Set's up the GCC compiler for a runner."

runs:
  using: "composite"
  steps:
    - name: Install GCC
      run: |
        if [[ $RUNNER_OS == Linux* ]]; then
          sudo apt install -y build-essential
        elif [[ $RUNNER_OS == Windows* ]]; then
          choco install mingw
        elif [[ $RUNNER_OS == macOS* ]]; then
          brew install gcc
        else
      shell: bash
