name: Use GCC
description: Sets up the GCC compiler for a runner.

runs:
  using: composite
  steps:
    - name: Install GCC
      run: |
        echo Attempting to install gcc for $RUNNER_OS
        if [[ $RUNNER_OS == Linux* ]]; then
          sudo apt update
          sudo apt install build-essential
          sudo apt install gcc g++ -y
        elif [[ $RUNNER_OS == Windows* ]]; then
          choco upgrade all
          choco install mingw
        elif [[ $RUNNER_OS == macOS* ]]; then
          brew update
          brew upgrade
          brew install gcc
        else
          echo Unsupported OS detected: $RUNNER_OS
          exit 1
        fi
        echo Installed successfully
      shell: bash

branding:
  icon: box
  color: blue
